// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Version2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005031017396_Version2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
