// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071619019_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
